title: DragonflAI Documentation
email: hannah@dragonflai.co
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
domain: dragonflai-tech.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://dragonflai-tech.github.io/sdk-docs-pages  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed